# Site metadata
base_url = "https://devtemp.xyz"
title = "devtemp.xyz"
description = "Static site for devtemp.xyz powered by Zola"

# Asset compilation
compile_sass = true

# Optional features
build_search_index = false

[markdown]
# Enable code highlighting for future code snippets
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
# Custom variables can live here
